name: Disc 1 CI

on:
  push:
    branches:
      - disc1-complete
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Godot (assumes you have a CLI build environment script)
      - name: Set up Godot
        run: |
          choco install godot --version=4.4.1.0

      # Build the installer (adjust your build commands as needed)
      - name: Build installer
        run: |
          ./build_scripts/build_installer.bat

      # Smoke test: launch the exe, load first scene, run a sample command
      - - name: Smoke test
  run: |
  .\build\LegendOfDragoon_Disc1.exe --test-mode

        continue-on-error: false

      # Calculate checksum
      - name: Calculate SHA-256
        id: checksum
        run: |
          certutil -hashfile build\LegendOfDragoon_Disc1_Setup.exe SHA256

      # Create or update a GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref == 'refs/heads/main' && 'nightly-' || '' }}${{ github.sha }}
          name: Build ${{ github.sha }}
          body: |
            Smoke test SHA256:
            ${{ steps.checksum.outputs.stdout }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
